import 'package:pokapp/main.dart';

const int absoluteStart = 1;
const int absoluteEnd = 1010;
const int kantoStart = 1;
const int kantoEnd = 151;
const int jhotoStart = 152;
const int jhotoEnd = 251;
const int hoennStart = 252;
const int hoennEnd = 386;
const int sinnohStart = 387;
const int sinnohEnd = 493;
const int unimaStart = 494;
const int unimaEnd = 649;
const int kalosStart = 650;
const int kalosEnd = 721;
const int aloaStart = 722;
const int aloaEnd = 809;
const int galarStart = 810;
const int galarEnd = 905;
const int paldeaStart = 906;
const int paldeaEnd = 1010;
