// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgTo_S8AJm9ttSLcZeByiQzP0Ju7QQc1M',
    appId: '1:685887848325:web:72db8ce99c888815dd0eec',
    messagingSenderId: '685887848325',
    projectId: 'pokapp-web',
    authDomain: 'pokapp-web.firebaseapp.com',
    storageBucket: 'pokapp-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtN3hsAI_YNJSEZ90PyMs8sgXj8yzDvCk',
    appId: '1:685887848325:android:946ef75f7c777b36dd0eec',
    messagingSenderId: '685887848325',
    projectId: 'pokapp-web',
    storageBucket: 'pokapp-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKrb6X_sGFhKjjs8Kr_i--qZyhxjzM2w',
    appId: '1:685887848325:ios:dc448e1f7ab07cd4dd0eec',
    messagingSenderId: '685887848325',
    projectId: 'pokapp-web',
    storageBucket: 'pokapp-web.appspot.com',
    iosClientId: '685887848325-85dbf9lsbdvf7nk5euf3llejrhh6lb9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKrb6X_sGFhKjjs8Kr_i--qZyhxjzM2w',
    appId: '1:685887848325:ios:dc448e1f7ab07cd4dd0eec',
    messagingSenderId: '685887848325',
    projectId: 'pokapp-web',
    storageBucket: 'pokapp-web.appspot.com',
    iosClientId: '685887848325-85dbf9lsbdvf7nk5euf3llejrhh6lb9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokapp',
  );
}
